---
- hosts: all
  become: yes
  tasks:
    - name: Mise a jour des packages
      apt:
        upgrade: "yes"
        update_cache: "yes"
    - name: Installation de iptables
      apt:
        name: iptables
        state: latest
    - name: Installation de apache2
      apt:
        name: apache2
        state: latest
    - name: Installation de php
      apt:
        name: php
        state: latest
    - name: Installation de php-mysqli
      apt:
        name: php-mysqli
        state: latest
      notify:
      - restart apache2
    - name: Installation de mariadb-server
      apt:
        name: mariadb-server
        state: latest
    - name: Installation de git
      apt:
        name: git
        state: latest
    - name: Installation de pip3
      apt:
        name: python3-pip
        state: latest
    - name: Suppression du fichier index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent
    - name: Clone du projet Photoblog
      ansible.builtin.git:
        repo: https://github.com/7ric/Photoblog.git
        dest: /var/www/html/
        update: no
    - name: Verification du al presence de pymysql
      become: true # needed if the other tasks are not played as root
      pip:
        name: pymysql
        state: present
    - name: Creation de la base de donnee Photoshop
      community.mysql.mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: import
        target: /var/www/html/photoblog.sql
        name: all
      ignore_errors: true
    - name: Modification des permissions du repertoire
      file:
        path: /var/www/html/
        owner: www-data
        group: www-data
        recurse: true
    - name: Affichage des erreurs dans php.ini
      lineinfile:
        dest: /etc/php/7.4/apache2/php.ini
        regexp: '^display_errors = Off'
        line: "display_errors = On"
        state: present
        backup: yes
    - name: Activation de disable_functions
      lineinfile:
        dest: /etc/php/7.4/apache2/php.ini
        regexp: '^disable_functions'
        line: "; disable_functions"
        state: present
        backup: yes
      notify:
      - restart apache2
  handlers:
    - name: restart apache2
      systemd:
        name: apache2
        state: restarted

    - name: Installation de cowsay
      apt:
        name: cowsay
        state: latest
    - name: Ajout du repertoire /usr/games dans la variable d environnement $PATH
      lineinfile:
        path: /root/.bashrc
        line: 'export PATH="$PATH:/usr/games/"'
        state: present
